{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "kgen.fullname" . }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kgen.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name | default (include "kgen.fullname" .) }}
  rules:
    - backendRefs:
        - name: {{ include "kgen.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}