{{- if .Values.priorityClass.enabled -}}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "kgen.fullname" . }}-priority
value: 1000000
globalDefault: false
description: "KGen generated PriorityClass"
{{- end }}