{{- if .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kgen.fullname" . }}-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kgen.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ .Chart.Name }}.rules
      rules:
        - alert: DeploymentReplicasMismatch
          expr: kube_deployment_spec_replicas{deployment="{{ include "kgen.fullname" . }}"} != kube_deployment_status_replicas_available{deployment="{{ include "kgen.fullname" . }}"}
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Deployment replicas mismatch for {{ include "kgen.fullname" . }}
{{- end }}