apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kgen.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kgen.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.statefulset.serviceName | default (include "kgen.fullname" .) }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kgen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kgen.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.statefulset.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.statefulset.storageSize | default "10Gi" }}