{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kgen.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kgen.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.istio.hosts | nindent 4 }}
  gateways:
    - {{ .Values.istio.gatewayName }}
  http:
    - route:
        - destination:
            host: {{ include "kgen.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}