package cmd

import (
	"fmt"

	"kgen/internal/tui"

	"github.com/spf13/cobra"
)

var explainCmd = &cobra.Command{
	Use:   "explain",
	Short: "Explain the purpose of generated Kubernetes resources",
	Long:  `Provide clear, simplified explanations for the standard Kubernetes resources generated by KGen.`,
	Run: func(cmd *cobra.Command, args []string) {
		cyan := tui.HeaderStyle.Render

		fmt.Println("\n" + tui.TitleStyle.Render(" Kubernetes Resource Explanations ") + "\n")

		resources := []struct {
			name, desc string
		}{
			{"Deployment", "Menjalankan dan mengelola replika aplikasi (Pod)."},
			{"Service", "Mengekspos port aplikasi secara internal di dalam cluster agar bisa diakses pod lain."},
			{"Ingress", "Mengatur lalu lintas HTTP/HTTPS dari luar cluster masuk ke Service (Load Balancer/Reverse Proxy)."},
			{"HPA (Horizontal Pod Autoscaler)", "Secara otomatis menambah atau mengurangi jumlah pod berdasarkan utilisasi CPU/Memory."},
			{"PDB (Pod Disruption Budget)", "Menjamin batas minimum pod yang harus tetap berjalan saat terjadi maintenance/eviction (Reliability)."},
			{"ServiceMonitor", "Mengkonfigurasi Prometheus untuk melakukan scraping metrik dari aplikasi (Monitoring)."},
			{"NetworkPolicy", "Mengatur lalu lintas jaringan masuk (ingress) dan keluar (egress) antar pod (Security)."},
			{"Secret", "Menyimpan data sensitif seperti password, API key, atau token secara terenkripsi di Kubernetes."},
			{"ExternalSecret", "Mengintegrasikan external secret manager (seperti AWS Secrets Manager, HashiCorp Vault) ke Kubernetes Secret."},
		}

		for _, res := range resources {
			fmt.Printf("%s\n├─ %s\n\n", cyan(res.name), res.desc)
		}
	},
}

func init() {
	rootCmd.AddCommand(explainCmd)
}
