package cmd

import (
	"fmt"

	"github.com/ihyamarsdev/kgen/internal/tui"

	"github.com/spf13/cobra"
)

var explainCmd = &cobra.Command{
	Use:   "explain",
	Short: "Explain the purpose of generated Kubernetes resources",
	Long:  `Provide clear, simplified explanations for the standard Kubernetes resources generated by KGen.`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("\n" + tui.TitleStyle.Render(" Kubernetes Resource Explanations ") + "\n")

		resources := []struct {
			name, desc string
		}{
			{"Deployment", "Manages and runs replicated instances of your application (Pods) with rolling updates and scaling."},
			{"Service", "Exposes application ports internally within the cluster so other Pods can discover and connect to them."},
			{"Ingress", "Manages external HTTP/HTTPS access to Services inside the cluster — acts as a reverse proxy or load balancer."},
			{"Gateway API", "The next-generation Kubernetes API for routing external traffic into the cluster (replaces Ingress in modern setups)."},
			{"HTTPRoute", "Defines routing rules for the Gateway API (path-based, header-based routing for HTTP traffic)."},
			{"HPA (Horizontal Pod Autoscaler)", "Automatically scales the number of Pods up or down based on CPU, memory, or custom metrics."},
			{"VPA (Vertical Pod Autoscaler)", "Automatically adjusts CPU and memory requests/limits for Pods based on historical usage."},
			{"KEDA (Kubernetes Event-Driven Autoscaler)", "Scales Pods based on external event sources like message queues, Kafka, cron schedules, or HTTP traffic."},
			{"PDB (Pod Disruption Budget)", "Ensures a minimum number of Pods remain available during voluntary disruptions like node maintenance or upgrades."},
			{"ConfigMap", "Stores non-sensitive configuration data (environment variables, config files) that can be mounted into Pods."},
			{"Secret", "Stores sensitive data like passwords, API keys, or TLS certificates in a base64-encoded format."},
			{"ExternalSecret", "Integrates external secret managers (AWS Secrets Manager, HashiCorp Vault, GCP Secret Manager) into Kubernetes Secrets."},
			{"SealedSecret", "Encrypts Kubernetes Secrets so they can be safely stored in version control (Bitnami Sealed Secrets)."},
			{"StatefulSet", "Manages stateful applications with stable Pod identities, ordered deployment, and persistent storage."},
			{"DaemonSet", "Ensures a copy of a Pod runs on every node (or a subset of nodes) in the cluster — used for logging, monitoring, or node agents."},
			{"CronJob", "Runs containerized jobs on a recurring schedule (like cron) — useful for backups, cleanup, or periodic tasks."},
			{"Job", "Runs a one-off task to completion — creates Pods that run until they succeed (or reach a retry limit)."},
			{"PVC (Persistent Volume Claim)", "Requests persistent storage from the cluster that survives Pod restarts — used for databases and stateful apps."},
			{"NetworkPolicy", "Controls inbound and outbound network traffic between Pods — provides pod-level firewall rules."},
			{"ServiceMonitor", "Configures the Prometheus Operator to automatically scrape metrics endpoints from your application."},
			{"PodMonitor", "Similar to ServiceMonitor but scrapes metrics directly from individual Pods (no Service required)."},
			{"PrometheusRule", "Defines alerting and recording rules for Prometheus — sets up alerts when metrics cross thresholds."},
			{"GrafanaDashboard", "Defines a pre-built Grafana dashboard for visualizing application metrics."},
			{"PriorityClass", "Assigns scheduling priority to Pods so critical workloads are scheduled before lower-priority ones."},
			{"ServiceAccount", "Provides an identity for Pods to authenticate with the Kubernetes API server."},
			{"Role", "Defines a set of permissions (verbs on resources) within a specific namespace."},
			{"RoleBinding", "Grants the permissions defined in a Role to a user, group, or ServiceAccount within a namespace."},
			{"ClusterRole", "Like Role but cluster-wide — used for cluster-level resources or across all namespaces."},
			{"ClusterRoleBinding", "Grants the permissions defined in a ClusterRole to a user, group, or ServiceAccount cluster-wide."},
			{"ArgoCD Application", "Declares a GitOps-managed application for ArgoCD — specifies the source repo, target cluster, and sync policy."},
			{"ArgoCD ApplicationSet", "Generates multiple ArgoCD Applications from a single template — useful for multi-environment or multi-tenant setups."},
			{"Flux HelmRelease", "Declares a Helm chart deployment managed by Flux CD — specifies chart source, values, and reconciliation interval."},
			{"Flux Kustomization", "Manages Kubernetes resource synchronization from a Git repository — applies kustomize overlays automatically."},
			{"Istio VirtualService", "Configures traffic routing rules for Istio service mesh — supports traffic splitting, retries, and fault injection."},
			{"Istio ServiceEntry", "Extends the Istio service mesh to include external services outside the cluster."},
		}

		for _, res := range resources {
			fmt.Printf("%s\n", tui.HeaderStyle.Render(res.name))
			fmt.Printf("  %s\n\n", res.desc)
		}
	},
}

func init() {
	rootCmd.AddCommand(explainCmd)
}
